### ISSUE TITLE
Load modules?

### ISSUE THREAD

**Issue by b3z** [BrandonZacharie/node-redis-server#18]
What's the best way to load a module like redisearch? 
Is there a way to it from node or only via redis-cli?

**Comment by BrandonZacharie** [comment]
> What's the best way to load a module like redisearch? 

There is no support for that now.

> Is there a way to it from node or only via redis-cli?

I'm unfamiliar with how modules work since I've never used them but I'll look in to it. If it can be done, I will try adding support for it in the next release.

**Comment by b3z** [comment]
Any news here?
