### ISSUE TITLE
spawn redis-server ENOENT

### ISSUE THREAD

**Issue by ramg9206** [BrandonZacharie/node-redis-server#2]
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: spawn redis-server ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:433:11)
    at startup (node.js:141:18)
    at node.js:977:3

**Comment by BrandonZacharie** [comment]
It looks like it can't find your redis binary. Have you checked your path?

**Comment by isaacdre** [comment]
I wrestled with this for more time than I wish to admit... I think the major issue I ran into is that I assumed that the redis binary was included when I ran the "npm install redis-server -s"

It would be rather helpful if the most recent stable binary was included, or there was documentation stating that one needs to download the redis binary.

Additionally in the documentation, it would be super helpful if there was an example on how to "stop" the redis server. The claim in the readme.md is that it "starts and stops the redis server".

One last thing: Adding some sample code that "sniffs" if the redis server is already up before attempting to launch it again? I'm just spitballing here, I know it should be as simple as throwing a "ping" and waiting for the "pong". But it would be nice to just be able to copy and paste and know its going to work.

All that being said. Thanks for creating this package, it helps take one more thing off my plate when launching my dev environments.

**Comment by BrandonZacharie** [comment]
This is great feedback! I will leave this issue open until each of these concerns are addressed. While including a binary is out of the scope of this module, providing better messaging in errors and documentation isn't. With that said, does the following outline summarize your proposal accurately?
- Add documentation on binary requirements
- Add documentation demonstrating how to stop a server
- Add support for and/or documentation on detecting port collisions

**Comment by isaacdre** [comment]
Oh man, I totally agree that including the binary is scope creep.

If you want to tackle those bullet points, that would be incredible!

Regards,

Isaac Dressman

**Comment by GGYaX** [comment]
The path don't work man, in your code, you didn't use path as argument to start redis.

**Comment by BrandonZacharie** [comment]
I'm adding support for custom paths this weekend.

**Comment by BrandonZacharie** [comment]
I've updated the documentation. Also, you may now provide a path to your binary.

**Comment by nijat13** [comment]
Hi @BrandonZacharie,  such a great lib!

Here's an issue that I faced.
I'm new in Redis, so sorry somehow stupid questions.
When I type `/usr/local/bin/redis-server` in terminal, it runs the Redis server. But this code doesn't work for me: 
```
const server = new RedisServer({
  port: 6379,
  bin: '/usr/local/bin/redis-server'
});
```
It throws an error: 
```
events.js:136
       throw er; // Unhandled 'error' event
       ^

 Error: spawn /usr/local/bin/redis-server ENOENT
```

Thanks in advance!

**Comment by nkn-ms** [comment]
Does anyone have the still same problem?
I had the same problem and  resolved.

I'm working in mac.

At first, there was not
/usr/local/bin/redis-server

so, 
`brew install redis`

after that there exists
/usr/local/bin/redis-server

problem was clear, that's all

**Comment by MartinDawson** [comment]
Yes I have the same problem, this library is trash. No good docs and it's just confusing.
