### ISSUE TITLE
Allow passing in additional command line parameters to redis-server

### ISSUE THREAD

**Issue by mattzuba** [BrandonZacharie/node-redis-server#4]
My particular use case is passing in a custom redis.conf file.

**Comment by BrandonZacharie** [comment]
This sounds quite useful!

**Comment by BrandonZacharie** [comment]
I believe https://github.com/BrandonZacharie/node-redis-server/pull/3 should address that use case. I'll keep this open until that's merged.

**Comment by BrandonZacharie** [comment]
This is available as 0.2.0 1fc7f13.
