### ISSUE TITLE
Timeout error during tests

### ISSUE THREAD

**Issue by CaleCrawford** [BrandonZacharie/node-redis-server#8]
When I clone the development branch and try to run the tests then begin failing at: 
`RedisServer #open() should start a server and execute a callback:`
The error is `Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.` but even if I increase the timeout to 5000ms the error still comes up. Is this happening for you or just me?

**Comment by andyish** [comment]
What version of Redis are you using? 

A couple of people experienced the same thing using Redis 4.0, downgraded to Redis 3.2.* and its fine. Not an ideal solution but we're using Redis 3.2.4 (AWS Elasticache) in production.

**Comment by BrandonZacharie** [comment]
I'll add information about supported versions to the README. Support for 4.0 is top of the road map.

**Comment by CaleCrawford** [comment]
That makes sense, thank you!
